# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
stages:
  - deviceBackup

"Custom Conf":
  stage: deviceBackup
  image: devops/ansible:bullseye
  before_script:
    - apt-get update && apt upgrade -y
    - which git || apt install git -y
    - apt install curl net-tools iputils-ping traceroute dnsutils iputils-ping openssh-server -y
    # - ansible-galaxy collection install community.sophos
  script:
    - ifconfig
    - traceroute 8.8.8.8
    - netstat
    - route
    - ping -c 4 10.1.254.251
    - ssh userita@10.1.254.251
    # - expect {
    #     Password { send "agoravita\r"}
    #     "#" send { send "enable\r" }
    #   }
