---
# ansible-playbook -i hosts test.yml 
# https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_command_module.html
- name: ansible-mikrotik
  hosts: mikrotik #all
  # become: yes
  gather_facts: no
#

  # vars:
  #   ansible_user: user
  #   ansible_ssh_pass: "password"
  #   ansible_connection: ansible.netcommon.network_cli
  #   ansible_network_os: cisco.ios.ios
  #   ansible_become: yes
  #   ansible_become_method: enable
  #   ansible_become_password: "password"

#ansible_become_pass: "{{ default_become_pass }}"

  roles:
    - role: mikrotik
